# Generated by Django 4.2.6 on 2024-01-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='remail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='semail',
            field=models.EmailField(default='virat18@gmail.com', max_length=254),
        ),
    ]
